version: '3.8'

services: 
  dev-social:
    container_name: server
    # image: node:12.18.2-stretch
    build: ./
    command: npm start
    working_dir: /c/My sites/docker
    environment: 
      REDIS_URI: redis://redis:6379
    links:
      - redis
    ports: 
      - "5000:5000"
    volumes: 
      - ./:/c/My sites/docker

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"